# -*- coding: utf-8 -*-
"""WorkSheet-0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jo4qXfIh-fNSgVKpkQ6J4hWgeaDw6tbk

WorkSheet-0

Task - 1:
Create a Python program that converts between different units of measurement.
"""

def convert_units(conversion_type, value):


    if conversion_type == "m_to_ft":
        return value * 3.28084

    elif conversion_type == "ft_to_m":
        return value / 3.28084

    elif conversion_type == "kg_to_lbs":
        return value * 2.20462

    elif conversion_type == "lbs_to_kg":
        return value / 2.20462

    elif conversion_type == "l_to_gal":
        return value * 0.264172

    elif conversion_type == "gal_to_l":
        return value / 0.264172

    else:
        return None


print("Choose conversion type")
print("1. Meters to Feet")
print("2. Feet to Meters")
print("3. Kilograms to Pounds")
print("4. Pounds to Kilograms")
print("5. Liters to Gallons")
print("6. Gallons to Liters")


choice = input("Enter choice (1-6): ")


try:

    value = float(input("Enter value: "))

    if choice == "1":
        result = convert_units("m_to_ft", value)
        print("Result:", result, "ft")

    elif choice == "2":
        result = convert_units("ft_to_m", value)
        print("Result:", result, "m")

    elif choice == "3":
        result = convert_units("kg_to_lbs", value)
        print("Result:", result, "lbs")

    elif choice == "4":
        result = convert_units("lbs_to_kg", value)
        print("Result:", result, "kg")

    elif choice == "5":
        result = convert_units("l_to_gal", value)
        print("Result:", result, "gal")

    elif choice == "6":
        result = convert_units("gal_to_l", value)
        print("Result:", result, "L")

    else:
        print("Invalid choice")


except ValueError:

    print("Invalid input. Please enter a numeric value.")

"""Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
"""

def find_sum(numbers):

    return sum(numbers)


def find_average(numbers):

    return sum(numbers) / len(numbers)


def find_max(numbers):

    return max(numbers)


def find_min(numbers):

    return min(numbers)


print("Choose operation")
print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")


choice = input("Enter choice (1-4): ")


try:

    user_input = input("Enter numbers separated by spaces: ")
    numbers = [float(num) for num in user_input.split()]

    if len(numbers) == 0:
        print("List is empty")

    elif choice == "1":
        result = find_sum(numbers)
        print("Sum:", result)

    elif choice == "2":
        result = find_average(numbers)
        print("Average:", result)

    elif choice == "3":
        result = find_max(numbers)
        print("Maximum:", result)

    elif choice == "4":
        result = find_min(numbers)
        print("Minimum:", result)

    else:
        print("Invalid choice")


except ValueError:
    print("Invalid input. Please enter numbers only.")

"""1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].
2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].
4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].
5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].
6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].
7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].
"""

def extract_every_other(lst):
    """
    Returns every other element starting from the first element.
    """
    return lst[::2]


def get_sublist(lst, start, end):
    """
    Returns a sublist from start index to end index (inclusive).
    """
    return lst[start:end+1]


def reverse_list(lst):
    """
    Returns the reversed list using slicing.
    """
    return lst[::-1]


def remove_first_last(lst):
    """
    Returns the list without the first and last elements.
    """
    return lst[1:-1]


def get_first_n(lst, n):
    """
    Returns the first n elements of the list.
    """
    return lst[:n]


def get_last_n(lst, n):
    """
    Returns the last n elements of the list.
    """
    return lst[-n:]


def reverse_skip(lst):
    """
    Returns elements in reverse order starting from the second last element and skipping one element.
    """
    return lst[-2::-2]


numbers = [1, 2, 3, 4, 5, 6]

print("Original List:", numbers)

print("Every other element:", extract_every_other(numbers))

print("Sublist (2 to 4):", get_sublist(numbers, 2, 4))

print("Reversed list:", reverse_list(numbers))

print("Without first and last:", remove_first_last(numbers))

print("First 3 elements:", get_first_n(numbers, 3))

print("Last 2 elements:", get_last_n(numbers, 2))

print("Reverse skip:", reverse_skip(numbers))

def flatten(lst):
    """Return a flattened list from a nested list."""
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)

    return result


def access_nested_element(lst, indices):
    """Return element from nested list using indices."""
    element = lst

    for i in indices:
        element = element[i]

    return element


def sum_nested(lst):
    """Return sum of all numbers in a nested list."""
    total = 0

    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item

    return total


def remove_element(lst, elem):
    """Remove all occurrences of elem from nested list."""
    result = []

    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)

    return result


def find_max(lst):
    """Return the maximum element in nested list."""
    max_value = None

    for item in lst:
        if isinstance(item, list):
            value = find_max(item)
        else:
            value = item

        if max_value is None or value > max_value:
            max_value = value

    return max_value


def count_occurrences(lst, elem):
    """Count occurrences of element in nested list."""
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1

    return count


def deep_flatten(lst):
    """Flatten a deeply nested list."""
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)

    return result


def average_nested(lst):
    """Return average of elements in nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)


nested = [[1, 2], [3, [4, 5]], 6]

print("Flatten:", flatten(nested))

print("Access element:", access_nested_element([[1,2,3],[4,5,6],[7,8,9]], [1,2]))

print("Sum:", sum_nested(nested))

print("Remove element:", remove_element([[1,2],[3,2],[4,5]], 2))

print("Max:", find_max(nested))

print("Count:", count_occurrences([[1,2],[2,3],[2,4]], 2))

print("Deep Flatten:", deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

print("Average:", average_nested([[1,2],[3,4],[5,6]]))

"""10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
"""

import numpy as np


empty_array = np.empty((2, 2))
print("Empty Array:")
print(empty_array)


ones_array = np.ones((4, 2))
print("\nAll Ones Array:")
print(ones_array)


full_array = np.full((3, 3), 7)
print("\nArray filled with value:")
print(full_array)


base_array = np.array([[1, 2], [3, 4]])

zeros_like_array = np.zeros_like(base_array)
print("\nZeros Like Array:")
print(zeros_like_array)


ones_like_array = np.ones_like(base_array)
print("\nOnes Like Array:")
print(ones_like_array)


new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)

print("\nList converted to Numpy Array:")
print(numpy_array)

"""Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.
"""

import numpy as np


arr1 = np.arange(10, 50)
print("Array from 10 to 49:")
print(arr1)


arr2 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix 0 to 8:")
print(arr2)


identity = np.eye(3)
print("\n3x3 Identity Matrix:")
print(identity)


random_arr = np.random.random(30)
print("\nRandom Array:")
print(random_arr)
print("Mean:", random_arr.mean())


arr10 = np.random.random((10, 10))
print("\n10x10 Random Array:")
print(arr10)
print("Minimum:", arr10.min())
print("Maximum:", arr10.max())


zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\nZero Array with 5th element replaced by 1:")
print(zero_arr)


arr = np.array([1, 2, 0, 0, 4, 0])
print("\nReversed Array:")
print(arr[::-1])


border = np.ones((5, 5))
border[1:-1, 1:-1] = 0
print("\n2D Array with border 1 and inside 0:")
print(border)


checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:")
print(checkerboard)

"""Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}
"""

import numpy as np


A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])


A_inv = np.linalg.inv(A)

result = np.dot(A, A_inv)

print("A * A^-1 = ")
print(result)


AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nAB = ")
print(AB)

print("\nBA = ")
print(BA)


print("\nAB != BA")
print(not np.array_equal(AB, BA))


AB_T = (np.dot(A, B)).T

BT_AT = np.dot(B.T, A.T)

print("\n(AB)^T = ")
print(AB_T)

print("\nB^T A^T = ")
print(BT_AT)


A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

B_eq = np.array([-1, -3, 9])


A_inv_eq = np.linalg.inv(A_eq)

X = np.dot(A_inv_eq, B_eq)

print("\nSolution [x y z] = ")
print(X)

"""10.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.
"""

import time
import numpy as np


size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()

result_list = [list1[i] + list2[i] for i in range(size)]

end = time.time()

print("Python List Addition Time:", end - start)


arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()

result_numpy = arr1 + arr2

end = time.time()

print("NumPy Addition Time:", end - start)

import time
import numpy as np


size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()

result_list = [list1[i] * list2[i] for i in range(size)]

end = time.time()

print("Python List Multiplication Time:", end - start)


arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()

result_numpy = arr1 * arr2

end = time.time()

print("NumPy Multiplication Time:", end - start)

import time
import numpy as np


size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()

dot_product = sum(list1[i] * list2[i] for i in range(size))

end = time.time()

print("Python List Dot Product Time:", end - start)


arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()

dot_numpy = np.dot(arr1, arr2)

end = time.time()

print("NumPy Dot Product Time:", end - start)

import time
import numpy as np


size = 1000

matrix1 = [[1]*size for _ in range(size)]
matrix2 = [[1]*size for _ in range(size)]

start = time.time()

result = [[0]*size for _ in range(size)]

for i in range(size):
    for j in range(size):
        for k in range(size):
            result[i][j] += matrix1[i][k] * matrix2[k][j]

end = time.time()

print("Python List Matrix Multiplication Time:", end - start)


A = np.ones((size, size))
B = np.ones((size, size))

start = time.time()

result_numpy = np.dot(A, B)

end = time.time()

print("NumPy Matrix Multiplication Time:", end - start)

import time
import numpy as np


size = 100

matrix1 = [[1]*size for _ in range(size)]
matrix2 = [[1]*size for _ in range(size)]

start = time.time()

result = [[0]*size for _ in range(size)]

for i in range(size):
    for j in range(size):
        for k in range(size):
            result[i][j] += matrix1[i][k] * matrix2[k][j]

end = time.time()

print("Python List Matrix Multiplication Time:", end - start)



size = 1000   # NumPy can handle large size

A = np.ones((size, size))
B = np.ones((size, size))

start = time.time()

result_numpy = np.dot(A, B)

end = time.time()

print("NumPy Matrix Multiplication Time:", end - start)